[workspace]
members = [
    "crates/kayton-front",
    "xtask",
]
resolver = "2"

[workspace.package]
edition = "2021"
license = "Apache-2.0 OR MIT"

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.metadata]
repository = "https://example.com/kayton"
