[package]
name = "kayton-host"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
kayton-abi = { path = "../kayton-abi" }
kayton-api = { path = "../kayton-api" }
thiserror = "1.0"

[lints]
workspace = true
