[package]
name = "kayton-bytecode"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
smol_str = { version = "0.2", features = ["serde"] }
thiserror = "1"

[dev-dependencies]
pretty_assertions = "1"
